@extends('layouts.app')
@section('title', 'Document Submission Deadline Reminders')
@section('content')
<div class="legacy-heading deadline-heading"><div><h1><i class="fa-solid fa-calendar-check"></i> Document Submission Deadline Reminders</h1><p>Review the submission schedule and instructions for your project documents.</p></div></div>
<section class="panel-card deadline-page-card">
    <div class="deadline-card-heading"><span class="deadline-heading-icon"><i class="fa-solid fa-clock"></i></span><div><span class="deadline-eyebrow">PROJECT SCHEDULE</span><h2>Schedule by Document Type</h2><p>Check each document deadline and its current status.</p></div></div>
    <div class="table-scroll"><table class="deadline-table"><thead><tr><th>#</th><th>Document Type</th><th>Description / Instructions</th><th>Deadline Date &amp; Time</th><th>Status</th></tr></thead><tbody>@forelse($deadlines as $deadline)@php($hasDate = $deadline->due_date && !str_starts_with($deadline->due_date, '0000-00-00')) @php($expired = $hasDate && \Illuminate\Support\Carbon::parse($deadline->due_date)->isPast())<tr><td>{{ $loop->iteration }}</td><td><strong><i class="fa-solid fa-file-lines deadline-file-icon"></i>{{ $deadline->title }}</strong></td><td>{{ $deadline->description ?: 'No additional instructions.' }}</td><td>{{ $hasDate ? \Illuminate\Support\Carbon::parse($deadline->due_date)->format('d/m/Y, h:i A') : 'To Be Announced' }}</td><td><span class="deadline-state {{ !$hasDate ? 'waiting' : ($expired ? 'expired' : 'active') }}">{{ !$hasDate ? 'Waiting for Admin' : ($expired ? 'Expired' : 'Active') }}</span></td></tr>@empty<tr><td colspan="5" class="deadline-empty">No submission deadlines have been posted yet.</td></tr>@endforelse</tbody></table></div>
    <div class="student-info-note"><i class="fa-solid fa-circle-info"></i> <strong>Student Notice:</strong> Submit the required document before the designated deadline. Milestone outcomes are recorded separately as verification statuses.</div>
</section>
@endsection
