@extends('layouts.app')
@section('title', 'Upload Project Documents')
@section('content')
<div class="legacy-heading"><div><h1>Upload Project Documents</h1><p>Submit each official DFT50114 rubric component as a PDF, DOCX, or ZIP file (maximum 100 MB).</p></div></div>
@php($documentTypes = ['A' => ['Proposal Presentation', '10%'], 'B' => ['Project Demonstration 1', '10%'], 'C' => ['Project Demonstration 2', '10%'], 'D' => ['Project Demonstration 3', '15%'], 'E' => ['Final Presentation - Poster', '15%'], 'F' => ['Final Presentation', '15%'], 'TECHNICAL_REPORT' => ['Technical Report', '15%']])
<div class="student-upload-grid">
    <section class="panel-card"><h2><i class="fa-solid fa-upload"></i> Upload Form</h2>@if($project)<form method="post" action="{{ route('student.documents.store') }}" enctype="multipart/form-data">@csrf
        <label>Document Type<select name="doc_type" required><option value="">-- Select Rubric Category --</option>@foreach($documentTypes as $code => [$label, $weight])<option value="{{ $code }}" @selected(old('doc_type') === $code) @disabled($documents->contains(fn ($document) => $document->doc_type === $code))>{{ $code }}: {{ $label }} ({{ $weight }}){{ $documents->contains(fn ($document) => $document->doc_type === $code) ? ' - Submitted by group member' : '' }}</option>@endforeach</select></label>
        <label>Choose File<input type="file" name="document_file" accept=".pdf,.docx,.zip" required></label><button class="button primary full" type="submit"><i class="fa-solid fa-cloud-arrow-up"></i> Upload Now</button></form>@else<p>Register your project before uploading documents.</p><a class="button primary" href="{{ route('student.projects.create') }}">Register Project</a>@endif</section>
    <section class="panel-card submitted-documents-card"><h2><i class="fa-solid fa-list"></i> Submitted Documents List</h2><div class="table-scroll"><table class="submitted-documents-table"><thead><tr><th>#</th><th>Rubric Category</th><th>Status</th><th>Upload Date</th><th>Action</th></tr></thead><tbody>@forelse($documents as $document)@php($documentLabels = ['A' => 'A: Proposal Presentation', 'B' => 'B: Project Demonstration 1', 'C' => 'C: Project Demonstration 2', 'D' => 'D: Project Demonstration 3', 'E' => 'E: Final Presentation - Poster', 'F' => 'F: Final Presentation', 'TECHNICAL_REPORT' => 'Technical Report'])<tr><td>{{ $loop->iteration }}</td><td><strong>{{ $documentLabels[$document->doc_type] ?? $document->doc_type }}</strong><small class="table-sub">{{ $document->original_name ?: 'Project document' }}</small></td><td><span class="document-status {{ strtolower($document->status) === 'pending' ? 'pending' : (strtolower($document->status) === 'approved' ? 'approved' : '') }}">{{ $document->status }}</span></td><td>{{ $document->uploaded_at ? \Illuminate\Support\Carbon::parse($document->uploaded_at)->format('d/m/Y h:i A') : '–' }}</td><td><a class="download-button" href="{{ route('documents.download', $document->id) }}"><i class="fa-solid fa-download"></i> Download</a></td></tr>@empty<tr><td colspan="5" class="empty-table">No documents have been submitted yet.</td></tr>@endforelse</tbody></table></div></section>
</div>
@endsection
