@extends('layouts.app')
@section('title', 'Student dashboard')
@section('content')
<div class="page-heading"><div><span class="eyebrow">STUDENT WORKSPACE</span><h1>Hello, {{ $user->full_name }}</h1><p>{{ $user->matric_no ?: 'Student' }} · {{ $user->program_name }}</p></div>@unless($project)<a class="button primary" href="{{ route('student.projects.create') }}">Register a project</a>@endunless</div>
@if($project)
<section class="panel-card project-summary"><div><span class="eyebrow">YOUR PROJECT · {{ $project->session }}</span><h2>{{ $project->title }}</h2><p>{{ $project->category }} · {{ $project->status }}</p><p>{{ $project->description }}</p><div class="team-list"><span class="eyebrow">PROJECT TEAM</span>@foreach($team as $member)<span>{{ $member->full_name }} <small>{{ $member->matric_no }} · {{ $member->role }}</small></span>@endforeach</div></div><div class="project-number">{{ $project->project_number ?: 'SPInE' }}</div></section>
<div class="content-grid"><section class="panel-card"><div class="section-head"><div><span class="eyebrow">SUBMISSIONS</span><h2>Project documents</h2></div></div>
@if($documents->isEmpty())<p class="empty-state">No documents have been submitted yet.</p>@else<div class="table-scroll"><table><thead><tr><th>Document</th><th>Submitted</th><th>Status</th><th></th></tr></thead><tbody>@foreach($documents as $document)<tr><td>{{ $document->original_name ?: $document->doc_type }}</td><td>{{ \Illuminate\Support\Carbon::parse($document->uploaded_at)->format('d M Y') }}</td><td><span class="status-pill">{{ $document->status }}</span></td><td><a href="{{ route('documents.download', $document->id) }}">Download</a></td></tr>@endforeach</tbody></table></div>@endif
<form class="upload-form" method="post" action="{{ route('student.documents.store') }}" enctype="multipart/form-data">@csrf<label>Submission type<select name="doc_type" required>@foreach(['A'=>'Proposal Presentation','B'=>'Project Demonstration 1','C'=>'Project Demonstration 2','D'=>'Project Demonstration 3','E'=>'Final Presentation - Poster','F'=>'Final Presentation','TECHNICAL_REPORT'=>'Technical Report'] as $key=>$label)<option value="{{ $key }}">{{ $label }}</option>@endforeach</select></label><label>File (PDF, DOCX or ZIP, max 100 MB)<input type="file" name="document_file" accept=".pdf,.docx,.zip" required></label><button class="button secondary" type="submit">Upload for review</button></form></section>
<aside class="panel-card"><span class="eyebrow">ASSESSMENT</span><h2>Current marks</h2><p class="score">{{ number_format((float)($marks->total_score ?? 0), 2) }}<small> / 100</small></p><h3>Upcoming deadlines</h3>@forelse($deadlines as $deadline)<div class="deadline"><strong>{{ $deadline->title }}</strong><small>{{ $deadline->due_date && !str_starts_with($deadline->due_date, '0000-00-00') ? \Illuminate\Support\Carbon::parse($deadline->due_date)->format('d M Y, g:i A') : 'Date to be announced' }}</small></div>@empty<p class="muted">No deadlines have been posted.</p>@endforelse</aside></div>
@else<section class="empty-project panel-card"><span class="eyebrow">YOUR WORKSPACE IS READY</span><h2>Register your project to begin.</h2><p>Add your project details and teammates, then upload your proposal and assessment documents here.</p><a class="button primary" href="{{ route('student.projects.create') }}">Register a project</a></section>@endif
@endsection
